### ISSUE TITLE
Add support for XEP-0045

### ISSUE THREAD

**Issue by tuduongquyet** [strophe/libstrophe#152]
Hi,
Multi User Chat is mandatory function for XMPP. Can you guys add support for XEP-0045?
XEP-0045 is described at https://xmpp.org/extensions/xep-0045.html

**Comment by jubalh** [comment]
You can implement it yourself in your project.
AFAIK libstrophe is about basic XMPP not about the XEPs. The project using libstrophe will implement the XEPs.
You can look at https://github.com/profanity-im/profanity/tree/master/src/xmpp for inspiration.

**Comment by pasis** [comment]
@tuduongquyet , as @jubalh mentioned, libstrophe implements XMPP core. Such a XEP can be implemented within application or as part of a separated project (lets say libstrophe-xeps).

**Comment by pasis** [comment]
Closing, because libstrophe won't implement XEPs other than related to authentication and stream management. This is because libstrophe is a low level library.

There are multiple requests for various XEPs, so I've been thinking about separated library for some time now. If it happens, these requests will be there in the backlog.
