### ISSUE TITLE
Not working with multiple FQDNs in DNS response

### ISSUE THREAD

**Issue by chen0627** [strophe/libstrophe#217]
Hi Team,

I am now using 0.9.3 but I have checked the latest version and found it should have same issue in it.

The mechanism in function xmpp_connect_client() which wants to try every FQDN from the DNS response is not working, because function _conn_connect() always returns 0 even the first FQDN of the list is not reachable.

What I expect is it should detect the connection is working or not and return an error code from _conn_connect(). 

![image](https://user-images.githubusercontent.com/6703516/198973854-8f924c39-1333-43b3-b4a4-16057d741591.png)

Could you please help on this issue?

Thanks.

**Comment by chen0627** [comment]
I was wondering if I can skip setting socket as NONBLOCK if xmpp_conn_type_t is XMPP_CLIENT? Then we can get the correct state after connect() return.

**Comment by sjaeckel** [comment]
IMO this is also related to #139

> I was wondering if I can skip setting socket as NONBLOCK if xmpp_conn_type_t is XMPP_CLIENT? Then we can get the correct state after connect() return.

Sure, you could change the code and set the socket as non-blocking and check if that works for you.
Make sure to set the socket to non-blocking after a successful connection, otherwise other things can&will not work as expected.

If you change it and it works for you, you could open a PR which adds this as an option (via e.g. a flag `XMPP_CONN_FLAG_NONBLOCKING_CONNECT`) instead of being hard-coded. I'll have a deeper look then whether it'd make sense if this gets merged or whether it'd make more sense to directly tackle #139 when there's time...

**Comment by chen0627** [comment]
I make changes on source code to set socket as blocking now and it works.

But a little thing that it takes a bit long to wait for timeout of connecting to the first FQDN, it is about 2 miniutes before libstrophe tries to connect the second FQDN. 

I may look further if I can still use non-blocking but with a flag in the timeout event and also in the function _conn_connect().

**Comment by pasis** [comment]
Try #221. It should resolve your issue, but it needs testing.

**Comment by fantomfp** [comment]
> Try #221. It should resolve your issue, but it needs testing.

It has been tested and it's working for that use-case.

**Comment by pasis** [comment]
Closing this issue since it's resolved in master. Re-open it if needed.
