### ISSUE TITLE
Additional dependencies to build on mac

### ISSUE THREAD

**Issue by ravindranathakila** [strophe/libstrophe#6]
Please include the following (optional) build tools to install for Mac OSX

brew install automake (which will fetch autoconf too)
brew install libtool

**Comment by pasis** [comment]
Installing libstrophe with homebrew should fetch/install all dependencies. If not, please contact the maintainer of respective homebrew package. I have removed OSX section from the README, because libstrophe has been added to many package managers and this is not the place to describe them all.

Autoconf, automake and libtool are mentioned in general requirements section now.

Regarding iOS build. Check out https://github.com/gameclosure/libstrophe-ios. Sorry, I don't know other attempts to build libstrophe for this platform.

Close this issue.
