### ISSUE TITLE
TLS error, 6

### ISSUE THREAD

**Issue by roselyndomingo** [strophe/libstrophe#62]
I get this error:
        xmpp DEBUG Unrecoverable TLS error, 6.
        xmpp DEBUG Closing socket.

**Comment by pasis** [comment]
Here is description of the error code:
```
SSL_ERROR_SSL

    A failure in the SSL library occurred, usually a protocol error.
The OpenSSL error queue contains more information on the error.
```

I think this is your post on stackoverflow: http://stackoverflow.com/questions/30772738/libstrophe-tls-unrecoverable-error-6

In order to investigate your problem:
 * Does this error occur with all servers or only certain ones?
 * Does it occur with a single connection and single thread?
 * Did you take into account that libstrophe is not thread-safe?
 * In case you have published your code somewhere, provide the link please.

You asked if you could handle the error. Libstrophe calls your callback on disconnect:
```
    conn->conn_handler(conn, XMPP_CONN_DISCONNECT, conn->error,
                       conn->stream_error, conn->userdata);
```
`conn->error` contains the tls error, but tls error codes are specific for tls implementation.

**Comment by pasis** [comment]
My bad, I posted wrong error description. Error 6 for openssl is:
```
SSL_ERROR_ZERO_RETURN

    The TLS/SSL connection has been closed. If the protocol version is
    SSL 3.0 or TLS 1.0, this result code is returned only if a closure alert
    has occurred in the protocol, i.e. if the connection has been closed
    cleanly. Note that in this case SSL_ERROR_ZERO_RETURN does
    not necessarily indicate that the underlying transport has been closed.
```

Just for reference. There is an example how to retrieve information from the openssl error queue: boothj5/profanity#770

Close due to inactivity.
