### ISSUE TITLE
Cannot add the same handler twice

### ISSUE THREAD

**Issue by degaart** [strophe/libstrophe#97]
Calling `xmpp_handler_add` twice with the same `handler` but different `userdata` doesn't work. The second call is ignored.

I need it because I'm writing a C++ wrapper for libstrophe and handlers are implemented as pure virtual classes with a static member function as `xmpp_handler`, which means every handler callback function has the same memory address, only the userdata changes.

**Comment by pasis** [comment]
For reference: https://github.com/metajack/libstrophe/issues/51

**Comment by pasis** [comment]
Adding same handler with different userdata is not a problem (actually coding part is done already). The problem is in `xmpp_handler_delete()` and similar functions: they accept only handler as argument. This means user can remove all handlers pointing to the same callback function, but there is no way to remove a particular couple (handler, userdata).

Of course we could stick to such an asymmetric interface, but I will think about more beautiful solution.

**Comment by pasis** [comment]
I pushed code to branch `multi-handler`: https://github.com/strophe/libstrophe/tree/multi-handler . I didn't check it though.

**Comment by degaart** [comment]
Tried it, and it worked flawlessly. Thank you.
